packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:
  '@modelcontextprotocol/inspector': ^0.5.1
  '@types/debug': ^4.1.12
  changelogen: ^0.0.0
  debug: ^4.4.0
  find-up: ^7.0.0
  pathe: ^2.0.3
  unimport: ^4.1.2
catalogs:
  prod:
    '@modelcontextprotocol/sdk': ^1.6.1
    h3: ^1.15.1
    vite-plugin-mcp: workspac
    zod: ^3.24.2
  nuxt:
    '@nuxt/kit': ^3.16.0
    '@nuxt/devtools': ^2.2.1
    '@nuxt/eslint-config': ^1.2.0
    '@nuxt/module-builder': ^0.8.4
    '@nuxt/schema': ^3.16.0
    '@nuxt/test-utils': ^3.17.2
    nuxt: ^3.16.0
  cli:
    '@antfu/eslint-config': ^4.8.1
    '@antfu/ni': ^23.3.1
    bumpp: ^10.0.3
    eslint: ^9.22.0
    lint-staged: ^15.4.3
    vue-tsc: ^2.2.8
    nodemon: ^3.1.9
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ~5.7.2
    unbuild: ^3.5.0
    vite: ^6.2.0
  testing:
    '@types/js-yaml': ^4.0.9
    js-yaml: ^4.1.0
    vitest-package-exports: ^0.1.1
    vitest: ^3.0.8
  types:
    '@types/node': latest
  utils:
    '@antfu/utils': ^9.1.0
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
