packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    '@antfu/eslint-config': ^4.14.1
    '@antfu/ni': ^24.4.0
    '@modelcontextprotocol/inspector': ^0.11.0
    bumpp: ^10.2.0
    eslint: ^9.29.0
    lint-staged: ^15.5.2
    nodemon: ^3.1.10
    simple-git-hooks: ^2.13.0
    tsx: ^4.20.3
    typescript: ~5.8.3
    unbuild: ^3.5.0
    vite: ^6.3.5
    vue-tsc: ^2.2.10
  nuxt:
    '@nuxt/devtools': ^2.5.0
    '@nuxt/eslint-config': ^1.4.1
    '@nuxt/kit': ^3.17.5
    '@nuxt/module-builder': ^1.0.1
    '@nuxt/schema': ^3.17.5
    '@nuxt/test-utils': ^3.19.1
    nitropack: ^2.11.12
    nuxi: ^3.25.1
    nuxt: ^3.17.5
  prod:
    '@modelcontextprotocol/sdk': ^1.12.3
    ansis: ^3.17.0
    async-cache-dedupe: ^2.2.0
    citty: ^0.1.6
    debug: ^4.4.1
    h3: ^1.15.3
    pathe: ^2.0.3
    unimport: ^5.0.1
    zod: ^3.25.67
  testing:
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.0
  types:
    '@types/debug': ^4.1.12
    '@types/node': latest
  utils:
    '@antfu/utils': ^9.2.0
    tinyexec: ^1.0.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
