name: Secrets Validation

on:
  workflow_dispatch:
  schedule:
    # Run monthly to check for token expiration
    - cron: '0 0 1 * *'

jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Docker Hub credentials
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "🐳 Validating Docker Hub credentials..."

          if [ -z "$DOCKERHUB_USERNAME" ]; then
            echo "❌ DOCKERHUB_USERNAME secret is not set"
            exit 1
          fi

          if [ -z "$DOCKERHUB_TOKEN" ]; then
            echo "❌ DOCKERHUB_TOKEN secret is not set"
            exit 1
          fi

          # Test Docker Hub authentication
          echo "$DOCKERHUB_TOKEN" | docker login docker.io -u "$DOCKERHUB_USERNAME" --password-stdin

          if [ $? -eq 0 ]; then
            echo "✅ Docker Hub authentication successful"
            docker logout docker.io
          else
            echo "❌ Docker Hub authentication failed"
            exit 1
          fi

      - name: Validate NPM token
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "📦 Validating NPM token..."

          if [ -z "$NPM_TOKEN" ]; then
            echo "❌ NPM_TOKEN secret is not set"
            exit 1
          fi

          # Set NPM token
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

          # Test NPM authentication
          if npm whoami --registry https://registry.npmjs.org/ >/dev/null 2>&1; then
            echo "✅ NPM authentication successful"
            USERNAME=$(npm whoami --registry https://registry.npmjs.org/)
            echo "📝 Authenticated as: $USERNAME"
          else
            echo "❌ NPM authentication failed"
            echo "💡 Check if token is an 'Automation' token with publish permissions"
            exit 1
          fi

          # Clean up
          rm ~/.npmrc

      - name: Validate GitHub token permissions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔐 Validating GitHub token permissions..."

          # Test repository access
          REPO_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                          "https://api.github.com/repos/${{ github.repository }}")

          if echo "$REPO_INFO" | grep -q '"permissions"'; then
            echo "✅ GitHub token has repository access"

            # Check specific permissions
            PERMISSIONS=$(echo "$REPO_INFO" | grep -A 10 '"permissions"')

            if echo "$PERMISSIONS" | grep -q '"push": true'; then
              echo "✅ GitHub token has push permissions"
            else
              echo "⚠️ GitHub token may not have push permissions"
            fi

            if echo "$PERMISSIONS" | grep -q '"admin": true'; then
              echo "✅ GitHub token has admin permissions"
            else
              echo "ℹ️ GitHub token does not have admin permissions (may be expected)"
            fi
          else
            echo "❌ GitHub token validation failed"
            exit 1
          fi

      - name: Generate validation report
        if: always()
        run: |
          echo "## 🔍 Secrets Validation Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Validation Date**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "**Repository**: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ **Status**: All secrets are valid and working" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Validated Secrets" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ DOCKERHUB_USERNAME" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ DOCKERHUB_TOKEN" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ NPM_TOKEN" >> $GITHUB_STEP_SUMMARY
            echo "- ✅ GITHUB_TOKEN" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Status**: Some secrets failed validation" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Action Required" >> $GITHUB_STEP_SUMMARY
            echo "Please check the workflow logs and update any invalid secrets." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Setup Guide" >> $GITHUB_STEP_SUMMARY
            echo "See [GitHub Environment Setup](./docs/GITHUB_ENVIRONMENT_SETUP.md) for detailed instructions." >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Validation" >> $GITHUB_STEP_SUMMARY
          echo "This validation runs automatically on the 1st of each month." >> $GITHUB_STEP_SUMMARY
          echo "You can also run it manually from the Actions tab." >> $GITHUB_STEP_SUMMARY
